version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed "s/refs\/heads\///")
      - docker build -t $intern .
      - docker tag intern $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$BRANCH_NAME
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$BRANCH_NAME
      - echo "Image pushed successfully!"
        - echo "Fetching SSH private key..."
      - aws ssm get-parameter --name /cicd/ssh --with-decryption --query "Parameter.Value" --output text > /tmp/ssh-key.pem
      - chmod 600 /tmp/ssh-key.pem

      - echo "Connecting to EC2 and deploying the new image..."
      - |
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh-key.pem ubuntu@3.72.77.241 << 'EOF'
        echo "Connected to EC2"
        cd /home/ubuntu/intern
        docker-compose down
        docker-compose up -d
        EOF
