# Stage 1: Build the React app
FROM 524291824362.dkr.ecr.eu-central-1.amazonaws.com/node:18-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Serve the app with Nginx
FROM 524291824362.dkr.ecr.eu-central-1.amazonaws.com/nginx:stable-alpine

# Remove default Nginx website
RUN rm -rf /usr/share/nginx/html/*

# Copy React build to Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Copy custom nginx config (optional, e.g. for React Router support)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
