FROM 524291824362.dkr.ecr.eu-central-1.amazonaws.com/node:18-alpine AS build
WORKDIR /app
COPY packages*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM 524291824362.dkr.ecr.eu-central-1.amazonaws.com/nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/confi.d/default.conf

CMD ["nginx", "-g", "daemon off;"]